# SwiftLint Configuration for LocationNewsSNS

# ルールの設定
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 無効化するルール
disabled_rules:
  - todo
  - line_length # 長い行を許可（コメントやURLなど）

# 除外するディレクトリとファイル
excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm
  - Package.swift

# 含めるディレクトリ
included:
  - ios-app/LocationNewsSNS

# カスタム設定
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - lat
    - lng
    - GPS

large_tuple:
  warning: 3
  error: 4

# ファイルヘッダー設定
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  LocationNewsSNS
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/

# カスタムルール
custom_rules:
  # SupabaseClientの直接使用を避ける
  no_direct_supabase_usage:
    name: "No Direct Supabase Usage"
    regex: 'SupabaseClient\('
    message: "SupabaseClient.shared を使用してください"
    severity: warning

  # TODO/FIXMEコメントの形式チェック
  todo_format:
    name: "TODO Format"
    regex: '\/\/\s*(TODO|FIXME)(?!:)'
    message: "TODO/FIXMEコメントには「:」を付けてください (例: // TODO: 説明)"
    severity: warning

  # ハードコードされたURLの検出
  no_hardcoded_urls:
    name: "No Hardcoded URLs"
    regex: 'https?:\/\/(?!.*\{)'
    message: "URLをハードコードしないでください。設定ファイルを使用してください"
    severity: warning
    excluded: ".*Test.*"

# アナライザールール
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration